### ISSUE TITLE
after borrow or return books, redirect to mainPage.

### ISSUE THREAD

**Issue by hygkui** [cloud-bean/cb3#12]
show msgPage, show tips to close this page
![msgPage](http://77flz7.com1.z0.glb.clouddn.com/2015/result.png?watermark/1/image/aHR0cDovL3dwamFtLnFpbml1ZG4uY29tL3dwamFtL3dhdGVybWFyay5wbmc=/dissolve/100/gravity/SouthEast/dx/10/dy/10|imageView2/2/w/600)

**Comment by xinnix** [comment]
#d554c97ca7581f3975e4fbbfafaf559b41f0123a
